// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcnVP8auEg2Rm1FHvHwkeJ_NB5iwZsSgw',
    appId: '1:779727848880:web:18491f36e6965cf2b00275',
    messagingSenderId: '779727848880',
    projectId: 'flutter-ecom-5c997',
    authDomain: 'flutter-ecom-5c997.firebaseapp.com',
    storageBucket: 'flutter-ecom-5c997.appspot.com',
    measurementId: 'G-4L6H3182ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2S4UwfzWvxcoh-APmYtt_32-P_STMe14',
    appId: '1:779727848880:android:5aad65634af90e4eb00275',
    messagingSenderId: '779727848880',
    projectId: 'flutter-ecom-5c997',
    storageBucket: 'flutter-ecom-5c997.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK1m0qxZrhXxMKm7uolsUs4TZUZemo9e0',
    appId: '1:779727848880:ios:5ac55ff41e033629b00275',
    messagingSenderId: '779727848880',
    projectId: 'flutter-ecom-5c997',
    storageBucket: 'flutter-ecom-5c997.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK1m0qxZrhXxMKm7uolsUs4TZUZemo9e0',
    appId: '1:779727848880:ios:5ac55ff41e033629b00275',
    messagingSenderId: '779727848880',
    projectId: 'flutter-ecom-5c997',
    storageBucket: 'flutter-ecom-5c997.appspot.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcnVP8auEg2Rm1FHvHwkeJ_NB5iwZsSgw',
    appId: '1:779727848880:web:cb8909a78e39c5ecb00275',
    messagingSenderId: '779727848880',
    projectId: 'flutter-ecom-5c997',
    authDomain: 'flutter-ecom-5c997.firebaseapp.com',
    storageBucket: 'flutter-ecom-5c997.appspot.com',
    measurementId: 'G-72V3QDV33R',
  );
}
